### ISSUE TITLE
Add price-spoofing security to purchase pages

### ISSUE THREAD

**Issue by dreamingmind** [dreamingmind/bindery#188]
To prevent the inconvenience of an order submission with a spoofed price:
- in sure on-page pricing is coming from a single data source
- re-calculate all pricing values on the server from the source after Add-to-cart request
- if the on-page derived price doesn't match the server-side derived price, have a plan
  - could have been an old page and pricing was updated since it's construction. An in-form date value could tell if this was an honest error.
  - if it wasn't honest, would it be worth processing the order with a message back to the user? Or just kill it and have them contact me might be better.
    - but in this case is it worth trying to block a user? I don't think I have technology for that and the likelyhood of this problem is so low that the labor probably would not be justified.

**Comment by curlyjason** [comment]
I think your concerns are justified and your method for handling spoofing seems solid. I esp. like the server side double check. On the response side, I think that the cancel and contact is the best method. You can word it well, maybe even offer a discount for their trouble. For the blocking, I think I would just have a basic outline done of what the block response options might be, so that if you needed to work relatively quickly, you didn't have to start with research.

**Comment by dreamingmind** [comment]
As I dug into the paypal api more, the spoofing risk may not be an issue. The price seems to be hidden and there is no way for a user to attempt to change it.

Still, my site calculates and displays a price. If a user messed with that in a miss-guided attempt to influence the purchase price I would want to know about it.

As to blocking... emails can easily be phonied up. And ip addresses might be fluid. What could I block?
